### ISSUE TITLE
weasel push: http support for mode 'wb' not implemented

### ISSUE THREAD

**Issue by justmars** [explosion/weasel#76]
Recently tried experimenting with weasel and so far so good save for the last part of saving trained models. 

Ran `weasel push` in two attempts: one endpoint url at R2 and another in S3 (they share some common apis) but getting the following error.

```sh
NotImplementedError: http support for mode 'wb' not implemented
```

The necessary keys (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY) are declared in `.env` and I have the following partial `project.yml` config:

```yml
...
commands:
  - name: "train"
    script:
    - prodigy train x x x
    deps:
    - config.cfg
    outputs:
    - training/${vars.name}/model-best

remotes:
  default: 'https://fullendpoint.url.here/bucket_name'
```

Not sure if it's faulty config on my part or if I missed something in the docs.
